### ISSUE TITLE
trying to use ServicePorts

### ISSUE THREAD

**Issue by tadanki** [martensson/nixy#28]
Nifty little tool guys!

I am trying to use Service Ports to define where to listen for each app, 
The nginx.tmpl example that nixy ships with shows : 
listen 7000; 

I am trying to get it to go like : 
                {{ $task := index $app.Tasks 0 }}
                {{ $servicePort := index $task.ServicePorts 0 }}
                  listen {{ $servicePort }};
But I have nothing being generated in the nginx.conf
Wondering if ServicePorts are being picked up right from marathon. 
I currently run Marathon +marathon lb which is serving this service port so i know that is configured right on Marathon.

Any pointers would be great !

**Comment by martensson** [comment]
Hi @tadanki, glad you like nixy! 

I guess what you are trying todo is running a L4 Loadbalancer instead of L7 (http/https), and bind each app to its own port through nginx. Did you check out the example template on how to achieve that? https://github.com/martensson/nixy/blob/master/nginx-stream.tmpl

If not the easiest way to find out the available variables inside the template is to just request nixy on `/v1/config` to get the full list.

**Comment by tadanki** [comment]
thanks for the pointer, /v1/config was very helpful!
