### ISSUE TITLE
Setting fail_timeout=0 to avoid downtime after Marathon deploy

### ISSUE THREAD

**Issue by tobiasgwaaler** [martensson/nixy#4]
Hi, Benjamin :)

I'm seeing a lot of 503 responses right after deploying an application with Marathon. I think it happens because after the deployment has successfully added the new app instance, both the old and the new app instances will be present in `upstream`, but Marathon will shortly thereafter kill the old instance. My current theory is that the new instance, although present in `upstream`, is marked as down by nginx while the old instance is still marked as up. Therefore traffic keeps being passed to the old instance and when Marathon kills the old instance there are no healthy apps left in `upstream`. That means it will take 10 seconds (the default `fail_timeout`) before the new instance is tried again. 

It would be interesting to see if adding `fail_timeout=0` to https://github.com/martensson/nixy/blob/master/nginx.tmpl#L32 could resolve this

What do you think?

**Comment by tobiasgwaaler** [comment]
I did some experimenting with nginx, and now I don't think my theory holds up. Even with a pretty high fail_timout, it behaves well. :/

**Comment by martensson** [comment]
Hi @tobiasgwaaler :)
Yes, we have already experimented a lot trying to get zero downtime, but the problem comes from Marathon and not nixy/nginx. We are not alone having these problems, check this issue:

https://github.com/mesosphere/marathon/issues/712 

Case is that Marathon behaves awfully strange sometimes when rolling out a new app. Lets assume we are running an app called foo v1, but we want to roll out foo v2.

Common events:
1. foo v1 is running fine.
2. foo v2 is being deployed, but still not healthy.
3. foo v1 is killed by marathon (ala kill -9) meaning it has no grace period. Also adds a small window when load balancers are not updated fast enough giving a few errors.
4. Load balancer now thinks no instances are running healthy creating a lot of errors.
5. foo v2 is marked healthy and things start working again.

Anyhow, this is an ongoing issue that nixy/nginx can't fix, and hopefully Marathon will attend this soon enough :disappointed:

**Comment by tobiasgwaaler** [comment]
Thanks :)
